name: Build APK
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platforms;android-29'
          ndk-version: '21.4.7075529'
      - name: Build APK
        run: g++ -o script.exe script.cpp
      - name: Generate APK
        run: aapt2 link --output apk.apk --manifest AndroidManifest.xml --no-version-vectors --debug-mode --auto-add-overlay --java com.example.script script.exe
      - name: Upload
